//본관
export const GET_ITEMS = "GET_ITEMS"
export const SELECT_ITEM = "SELECT_ITEM"
export const PUSH_PREVIOUS_DIRECTORY = "PUSH_PREVIOUS_DIRECTORY"
export const POP_PREVIOUS_DIRECTORY = "POP_PREVIOUS_DIRECTORY"
export const CLEAR_PREVIOUS_DIRECTORIES = "CLEAR_PREVIOUS_DIRECTORIES"
export const CLEAR_ERROR = "CLEAR_ERROR"


//팝업
export const GET_ITEMS_MODAL = "GET_ITEMS_MODAL"
export const SELECT_ITEM_MODAL = "SELECT_ITEM_MODAL"
export const PUSH_PREVIOUS_DIRECTORY_MODAL = "PUSH_PREVIOUS_DIRECTORY_MODAL"
export const POP_PREVIOUS_DIRECTORY_MODAL = "POP_PREVIOUS_DIRECTORY_MODAL"
export const CLEAR_PREVIOUS_DIRECTORIES_MODAL = "CLEAR_PREVIOUS_DIRECTORIES_MODAL"
export const CLOSE_OR_OPEN_MODAL = "CLOSE_OR_OPEN_MODAL"

